#! /bin/bash
#
# Confirms that a commit message does not exceed 72 characters for any line and suggests one if it does.
#

readonly MAX_LINE_LENGTH=72
readonly VERSION="commit-msg 0.1.0"

while getopts ":v-:" opt; do
	case $opt in
		-)
			case "${OPTARG}" in
				version)
					echo "$VERSION"
					exit 0
					;;
                *)
                    echo "Invalid option --${OPTARG}" >&2
                    exit 1
                    ;;
			esac
			;;
		v)
			echo "$VERSION"
			exit 0
			;;
        \?) echo "Invalid option: -$OPTARG" >&2; exit 1;;
        *)  echo "Unimplemented option: -$opt" >&2; exit 1;;
	esac
done
OPTIND=1

corrected=''
ok=true
while IFS='' read -r line || [[ -n "$line" ]]; do
    if (( "${#line}" > "$MAX_LINE_LENGTH" )) && [[ "$line" != \#* ]] ; then
        corrected+="$(echo "$line" | fold -w "$MAX_LINE_LENGTH" -s)\n"
        ok=false
    elif [[ "$line" != \#* ]]; then
        corrected+="$line\n"
    fi
done < "$1"

if [[ "$ok" == false ]]; then
    echo "error: maximum line length exceeded" >&2
    echo "error: all lines must be less than or equal to $MAX_LINE_LENGTH characters" >&2
    echo "error: use --no-verify to skip this check next time"
    echo "consider:" >&2
    echo "$(echo -e "$corrected")" >&2 # the nested echo is a cheap hack to remove multiple trailing new lines
    exit 1
fi
